### ISSUE TITLE
activity 4

### ISSUE THREAD

**Issue by siandav** [ironhack-edu/data_2.01_activities#1]
for my class i will ignore the first 2 in here as do not think they are very relevant 

i have rephrased the instructions according with whats easier to understand @sandrabosk 

1. GNORE The select statement is used as a print command in SQL. Use the select statement to print "Hello World".
2. IGNORE Use the select statement to perform a simple mathematical calculation to add two numbers.
3. Use an appropriate Select statement to retrieve a list of unique card types from the bank database. 
4. Get a list of all the district names in the bank database - I suggest using the case study extended here to work out which column is required here because we are looking for the names of places, not just the IDs. it would be great to see the results under the heading ‘district name’ (hint: use an alias) - you should have 77 rows 
5. Revise your query to also show the Region, and limit the results to just 30 rows 
6. BONUS : sort the results alphabetically by district name A>Z before selecting the 30

**Comment by sandrabosk** [comment]
Thank you, @siandav. I just updated rephrased ones and regarding the ignored ones, it is completely ok that each instructor has their own approach to what they consider as more or less important for the current group. I assume that from group to group you will have also a different approach to what is important, so, for now, I will keep them but if needed, definitely we will remove them for the next group.

Also, please send us the solution for the last added iterations (5 with the bonus).

**Comment by ironhack-edu** [comment]
@siandav [Solution file](https://gist.github.com/ironhack-edu/dce29559311a9c6aafcb36e76978e89d) updated also. Ignore the request to send us a solution. Thanks.
